### ISSUE TITLE
Checklist for release 2.0

### ISSUE THREAD

**Issue by AntonPetrov** [RNAcentral/R2DT#145]
- [x] Make sure all tests pass
- [x] Generate precomputed library
- [x] Update version info in Readme and shared.py
- [ ] Merge pull request
- [ ] Check that Docker Hub updated the `latest` image
- [ ] Publish GitHub release
- [ ] Publish blog post
- [ ] Update Timeline Google Doc
- [ ] Deploy new web app on rnacentral.org
- [ ] Deploy the latest image on Job Dispatcher and test the API
- [ ] Tweet
- [ ] Create a checklist for the next release
