### ISSUE TITLE
Checklist for release 1.3

### ISSUE THREAD

**Issue by AntonPetrov** [RNAcentral/R2DT#82]
- [x] Make sure all tests pass
- [x] Upload precomputed library to the EBI FTP
- [x] Update version info in Readme and shared.py
- [x] Merge pull request
- [x] Check that Docker Hub updated the `latest` image
- [x] Deploy the latest image on Job Dispatcher and test the API
- [x] Deploy new web app on rnacentral.org
- [x] Publish GitHub release
- [x] Publish blog post
- [x] Tweet
- [x] Create a checklist for the next release
