### ISSUE TITLE
Checklist for release 1.4

### ISSUE THREAD

**Issue by AntonPetrov** [RNAcentral/R2DT#86]
- [x] Make sure all tests pass
- [x] Upload precomputed library to the EBI FTP
- [x] Update version info in Readme and shared.py
- [x] Merge pull request
- [x] Check that Docker Hub updated the `latest` image
- [x] Publish GitHub release
- [x] Publish blog post
- [x] Update Timeline Google Doc
- [ ] Deploy new web app on rnacentral.org
- [ ] Deploy the latest image on Job Dispatcher and test the API
- [ ] Tweet
- [ ] Create a checklist for the next release
